name: Build PS3SHH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download ps3dev toolchain
        run: |
          wget -q https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz
          sudo tar -xzf ps3dev-ubuntu-latest-2020-08-31.tar.gz -C /usr/local
          rm ps3dev-ubuntu-latest-2020-08-31.tar.gz

      - name: Set environment
        run: |
          echo "PS3DEV=/usr/local/ps3dev"  >> $GITHUB_ENV
          echo "PSL1GHT=/usr/local/ps3dev" >> $GITHUB_ENV
          echo "/usr/local/ps3dev/bin"      >> $GITHUB_PATH
          echo "/usr/local/ps3dev/ppu/bin"  >> $GITHUB_PATH

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python2 libelf-dev zlib1g-dev
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Build PS3SHH PKG
        run: make pkg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS3SHH-Package
          path: PS3SHH.pkg
